### ISSUE TITLE
Documentation Please

### ISSUE THREAD

**Issue by rohitgcs** [infoxchange/supervisor-logging#9]
Is there a place where how we can use this is documented?
Thanks

**Comment by matmunn** [comment]
I've clarified the `supervisord.conf` file in the readme, all other config is already documented there.

**Comment by rohitgcs** [comment]
@matmunn No I understand that - but it doesn't explain where the syslogs go after configuration and where the configs for that are. Also if you could tell me where that is I could help in adding some more details around usage through a PR. Thanks.

**Comment by matmunn** [comment]
This package is used to send logs to a remote syslog instance across the network, configuring that syslog instance is beyond the scope of this package and is OS-dependent.
